Add sample svg for mx vertical
libratbag/piper pull request #577
Opened 2020-09-24 20:06 UTC by faridgh1991

sample svg for MX Vertical added, it is copy of g403's svg that i removed extra buttons.we need to replace it by a correct svg. #539

2020-10-10 18:20 UTC, Lucs1590 approved these changes

2020-11-25 13:15 UTC, FFY00 requested changes
Hi, this is just a copy of the G403 SVG without the logo.

2020-11-26 07:35 UTC, faridgh1991 commented
> Hi, this is just a copy of the G403 SVG without the logo.

Hi, I know! but it's better than 404 error! i prefer using this while correct SVG is not exists.

2021-07-24 20:41 UTC, FFY00 commented
Superseded by #606

2021-07-24 20:41 UTC, closed without merging